apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-svc-deployment
  labels:
    app: social-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-svc
  template:
    metadata:
      labels:
        app: social-svc
    spec:
      containers:
        - name: social-svc
          image: kotlangauthsvc.azurecr.io/social-service:latest
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongoUri
            - name: ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: accessSecret
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: awsAccessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: awsSecretAccessKey
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secrets
                  key: azureStorageAccount
            - name: AZURE_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secrets
                  key: azureStorageAccessKey
          ports:
            - containerPort: 8081
              name: web
            - containerPort: 50051
              name: grpc
