apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-svc-deployment
  labels:
    app: social-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-svc
  template:
    metadata:
      labels:
        app: social-svc
    spec:
      containers:
        - name: social-svc
          image: sainageswar/kotlang-social:latest
          env:
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-ad
                  key: tenantId
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-ad
                  key: clientId
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-ad
                  key: clientSecret
          ports:
            - containerPort: 8081
              name: web
            - containerPort: 50051
              name: grpc
